import { createHash } from "node:crypto";
import type { Plugin } from "vite";

/** Minimal shape of a Rollup output chunk/asset used for precache sizing. */
export interface EmittedBundleFile {
  type: string;
  fileName: string;
  code?: string;
  source?: string | Uint8Array;
}

/**
 * Build-time PWA service worker (P6-01).
 *
 * Decision (recorded in ARCHITECTURE.md §11): a small hand-rolled service
 * worker generated by this Vite plugin, instead of vite-plugin-pwa. The
 * app's caching needs are narrow (offline app shell + static assets;
 * API stays network-only), so a ~60-line worker with an explicit strategy
 * is easier to audit than a plugin's generated output, and it adds no
 * dependency. P6-02 will layer the offline mutation queue on top.
 *
 * Strategy:
 * - install: precache the app shell ("/", "/index.html", icons, manifest)
 *   plus small hashed build assets; skipWaiting so the new shell activates.
 * - activate: delete stale caches, claim clients.
 * - fetch:
 *   - non-GET and API traffic (/rest/, /auth/) → network only. The
 *     ledger is the source of truth; stale API responses are never served.
 *   - navigations → network first, falling back to the cached app shell
 *     (this is the offline shell).
 *   - same-origin static assets → cache first (they are content-hashed),
 *     populating the cache on miss — this is how large bundles reach the
 *     cache without going through the install precache.
 */

/** Shell files copied from public/ that the worker must precache. */
const SHELL_FILES = [
  "/",
  "/index.html",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/icons/apple-touch-icon-180.png",
  "/icons/favicon-32.png",
];

/**
 * Maximum install-precache asset size. Empirically (Chromium 1243, P6-01),
 * putting a ~1MB file through the install-time cache.addAll() leaves the
 * worker "activated" but unable to take control of any client, while 512KB
 * is fine. Large bundles are cached during activate instead (LAZY_URLS),
 * with a wide margin — and the fetch handler also populates the cache on
 * first use as a backstop.
 */
export const MAX_PRECACHE_BYTES = 256 * 1024;

function emittedByteSize(item: EmittedBundleFile): number {
  if (typeof item.code === "string") return Buffer.byteLength(item.code, "utf8");
  const source = item.source;
  if (typeof source === "string") return Buffer.byteLength(source, "utf8");
  return source?.byteLength ?? 0;
}

export interface PrecacheSelection {
  /** Small assets precached during install. */
  precache: string[];
  /** Large assets cached during activate (see MAX_PRECACHE_BYTES). */
  lazy: string[];
}

/**
 * Split bundle assets for the worker: every emitted chunk/asset except
 * sw.js itself; small files go to the install precache, oversized ones
 * are cached lazily during activate.
 */
export function selectPrecacheAssets(
  bundle: Record<string, EmittedBundleFile>,
): PrecacheSelection {
  const precache: string[] = [];
  const lazy: string[] = [];
  for (const item of Object.values(bundle)) {
    if (item.type !== "asset" && item.type !== "chunk") continue;
    if (item.fileName === "sw.js") continue;
    if (emittedByteSize(item) <= MAX_PRECACHE_BYTES) {
      precache.push(item.fileName);
    } else {
      lazy.push(item.fileName);
    }
  }
  return { precache, lazy };
}

/**
 * Build the sw.js source. `precacheAssets` are cached during install;
 * `lazyAssets` (large bundles) are cached during activate — see
 * MAX_PRECACHE_BYTES.
 */
export function buildServiceWorkerSource(
  precacheAssets: string[],
  lazyAssets: string[] = [],
): string {
  const assets = [...new Set(precacheAssets)].sort();
  const lazy = [...new Set(lazyAssets)].sort();
  const version = createHash("sha256")
    .update([...assets, ...lazy].join("\n"))
    .digest("hex")
    .slice(0, 12);
  const precache = [...SHELL_FILES, ...assets.map((p) => `/${p}`)];
  const lazyUrls = lazy.map((p) => `/${p}`);

  return `/* Restaurant Inventory service worker (P6-01) — generated at build time. */
const CACHE_NAME = "ri-shell-${version}";
const PRECACHE_URLS = ${JSON.stringify(precache)};
const LAZY_URLS = ${JSON.stringify(lazyUrls)};

self.addEventListener("install", (event) => {
  // NOTE: skipWaiting() is called synchronously and NOT awaited inside
  // waitUntil — its promise only resolves after install completes, so
  // awaiting it here would deadlock the worker in "activating" forever.
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim())
      // Large bundles are cached here rather than during install: a ~1MB
      // install-time addAll() leaves the worker unable to take control
      // (see MAX_PRECACHE_BYTES). Best-effort — activation must succeed
      // even if this fetch fails (e.g. updating while offline).
      .then(() =>
        caches
          .open(CACHE_NAME)
          .then((cache) => cache.addAll(LAZY_URLS))
          .catch(() => undefined),
      ),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  // API traffic is the source of truth — never serve it from cache.
  if (url.pathname.startsWith("/rest/") || url.pathname.startsWith("/auth/")) return;
  if (request.mode === "navigate") {
    // Offline shell: network first, cached app shell on failure.
    event.respondWith(
      fetch(request).catch(() =>
        caches.match("/index.html").then((res) => res ?? caches.match("/")),
      ),
    );
    return;
  }
  if (url.origin !== self.location.origin) return;
  // The worker script itself must never be cached: Chromium re-fetches it
  // on every navigation to check for updates, and a cached copy would pin
  // the app to a stale worker forever.
  if (url.pathname === "/sw.js") return;
  // Hashed static assets: cache first, populate on miss. ignoreVary is
  // required because servers may send "Vary: Origin" while the precache
  // request and the page's CORS-mode subresource requests carry different
  // Origin headers — the bytes are content-hashed so they never vary.
  event.respondWith(
    caches.match(request, { ignoreVary: true }).then(
      (cached) =>
        cached ??
        fetch(request).then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        }),
    ),
  );
});
`;
}

/** Vite plugin emitting the generated sw.js into the build output. */
export function pwaServiceWorkerPlugin(): Plugin {
  return {
    name: "ri-pwa-service-worker",
    apply: "build",
    generateBundle(_options, bundle) {
      const { precache, lazy } = selectPrecacheAssets(bundle);
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: buildServiceWorkerSource(precache, lazy),
      });
    },
  };
}
